// Code generated by goyacc -o macro.go macro.y. DO NOT EDIT.

//line macro.y:2
package parser

import __yyfmt__ "fmt"

//line macro.y:2

import ()

//line macro.y:9
type yySymType struct {
	yys    int
	node   yaccMacroNode
	bool   bool
	number interface{}
	string string
}

const token_number = 57346
const token_string = 57347
const token_identifier = 57348
const token_bool = 57349
const DefinitionKeyword = 57350
const SyntaxKeyword = 57351
const MacroKeyword = 57352
const BracketOpen = 57353
const BracketClose = 57354
const BraceOpen = 57355
const BraceClose = 57356
const Comma = 57357
const Colon = 57358
const Semicolon = 57359
const Equal = 57360
const GreaterThan = 57361
const LessThan = 57362
const Dash = 57363
const Dot = 57364
const Arrow = 57365
const ParenOpen = 57366
const ParenClose = 57367
const Eol = 57368

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"token_number",
	"token_string",
	"token_identifier",
	"token_bool",
	"DefinitionKeyword",
	"SyntaxKeyword",
	"MacroKeyword",
	"BracketOpen",
	"BracketClose",
	"BraceOpen",
	"BraceClose",
	"Comma",
	"Colon",
	"Semicolon",
	"Equal",
	"GreaterThan",
	"LessThan",
	"Dash",
	"Dot",
	"Arrow",
	"ParenOpen",
	"ParenClose",
	"Eol",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line macro.y:205

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 112

var yyAct = [...]int8{
	38, 62, 54, 3, 35, 7, 9, 19, 11, 34,
	65, 23, 13, 21, 15, 25, 47, 28, 43, 16,
	10, 17, 10, 46, 5, 42, 24, 10, 10, 21,
	30, 31, 44, 29, 10, 71, 45, 49, 20, 52,
	48, 10, 51, 50, 32, 70, 59, 43, 6, 20,
	87, 64, 46, 82, 42, 52, 73, 44, 66, 69,
	44, 44, 60, 68, 5, 45, 76, 5, 84, 78,
	67, 77, 79, 81, 43, 85, 72, 83, 86, 46,
	26, 42, 74, 55, 63, 75, 55, 88, 44, 56,
	18, 53, 45, 12, 10, 2, 58, 8, 1, 61,
	41, 36, 80, 40, 57, 39, 37, 33, 27, 22,
	14, 4,
}

var yyPact = [...]int16{
	38, 38, -2, -6, -2, -1000, 87, -6, -2, -6,
	-1000, 1, -1000, -6, -1000, -2, 15, 84, 23, 3,
	-1000, -1000, -2, 67, 8, 23, -2, -2, 67, -13,
	68, 2, 23, 41, 12, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, 77, -1000, 83, 40, 78, -2, -13, -4,
	12, -13, -1000, -1000, 56, 43, 80, 20, 65, -1000,
	34, 70, -1000, 80, -6, -1000, -13, -1000, 80, 50,
	-1000, 37, 37, 31, -1000, 78, -1000, 49, -1000, -1000,
	63, -1000, -1000, -1000, -1000, 25, 37, -1000, -1000,
}

var yyPgo = [...]int8{
	0, 95, 111, 110, 109, 108, 15, 107, 2, 9,
	4, 0, 106, 105, 104, 103, 102, 101, 100, 99,
	1, 98, 3, 7, 96,
}

var yyR1 = [...]int8{
	0, 22, 22, 22, 23, 23, 24, 21, 21, 21,
	21, 1, 2, 3, 4, 4, 5, 5, 6, 7,
	7, 7, 9, 9, 10, 10, 10, 10, 10, 10,
	12, 11, 13, 14, 14, 18, 19, 19, 20, 20,
	15, 16, 16, 17, 17, 8, 8,
}

var yyR2 = [...]int8{
	0, 1, 2, 0, 1, 2, 3, 2, 2, 1,
	3, 3, 2, 11, 3, 0, 3, 0, 5, 2,
	3, 0, 1, 2, 1, 1, 1, 1, 1, 1,
	1, 4, 3, 1, 3, 3, 1, 3, 1, 2,
	6, 1, 3, 2, 3, 1, 4,
}

var yyChk = [...]int16{
	-1000, -21, -1, -22, -2, 26, 10, -22, -1, -22,
	26, -22, 6, -22, -3, 13, -22, 6, 6, -23,
	26, 26, -4, 8, -22, -6, 13, -5, 9, -23,
	-22, -22, -6, -7, -9, -10, -17, -12, -11, -13,
	-15, -18, 13, 6, 20, 24, 11, 14, -23, -22,
	-9, -23, -10, 14, -8, 6, 6, -14, -24, -11,
	22, -19, -20, 6, -22, 14, -23, 14, 20, -8,
	25, 15, 11, 22, 12, 15, -8, -8, 19, -11,
	-16, -11, 22, -20, 19, 12, 15, 25, -11,
}

var yyDef = [...]int8{
	3, -2, 3, 9, 3, 1, 0, 8, 3, 7,
	2, 0, 12, 10, 11, 3, 0, 0, 0, 15,
	4, 5, 3, 0, 17, 0, 3, 3, 0, 14,
	21, 0, 0, 3, 0, 22, 24, 25, 26, 27,
	28, 29, 0, 30, 0, 0, 0, 3, 16, 0,
	0, 19, 23, 43, 0, 45, 0, 0, 0, 33,
	0, 0, 36, 38, 13, 18, 20, 44, 0, 0,
	32, 0, 0, 0, 35, 0, 39, 0, 31, 34,
	0, 41, 6, 37, 46, 0, 0, 40, 42,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 7:
		yyDollar = yyS[yypt-2 : yypt+1]
//line macro.y:48
		{
			registerRootNode(yylex, yyDollar[1].node)
		}
	case 10:
		yyDollar = yyS[yypt-3 : yypt+1]
//line macro.y:53
		{
			registerRootNode(yylex, yyDollar[2].node)
		}
	case 11:
		yyDollar = yyS[yypt-3 : yypt+1]
//line macro.y:59
		{
			yyVAL.node = appendNode(NodeOpMacro, yyDollar[1].node, yyDollar[3].node)
		}
	case 12:
		yyDollar = yyS[yypt-2 : yypt+1]
//line macro.y:64
		{
			yyVAL.node = appendNode(NodeOpSignature, newNode(NodeOpName, yyDollar[2].string))
		}
	case 13:
		yyDollar = yyS[yypt-11 : yypt+1]
//line macro.y:76
		{
			assertEqual(yylex, yyDollar[3].string, "kind", "First identifier in macro body must be 'kind'")
			yyVAL.node = appendNode(NodeOpBody, newNode(NodeOpKind, yyDollar[4].string), yyDollar[6].node, yyDollar[8].node)
		}
	case 14:
		yyDollar = yyS[yypt-3 : yypt+1]
//line macro.y:82
		{
			yyVAL.node = appendNode(NodeOpDefinition, yyDollar[2].node)
		}
	case 15:
		yyDollar = yyS[yypt-0 : yypt+1]
//line macro.y:86
		{
			yyVAL.node = appendNode(NodeOpDefinition)
		}
	case 16:
		yyDollar = yyS[yypt-3 : yypt+1]
//line macro.y:91
		{
			yyVAL.node = appendNode(NodeOpSyntax, yyDollar[2].node)
		}
	case 17:
		yyDollar = yyS[yypt-0 : yypt+1]
//line macro.y:95
		{
			yyVAL.node = appendNode(NodeOpSyntax)
		}
	case 18:
		yyDollar = yyS[yypt-5 : yypt+1]
//line macro.y:101
		{
			yyVAL.node = yyDollar[3].node
		}
	case 19:
		yyDollar = yyS[yypt-2 : yypt+1]
//line macro.y:105
		{
			yyVAL.node = appendNode(NodeOpBody, yyDollar[1].node)
		}
	case 20:
		yyDollar = yyS[yypt-3 : yypt+1]
//line macro.y:108
		{
			yyVAL.node = appendNodeTo(&yyDollar[1].node, yyDollar[2].node)
		}
	case 21:
		yyDollar = yyS[yypt-0 : yypt+1]
//line macro.y:111
		{
			yyVAL.node = appendNode(NodeOpBody)
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
//line macro.y:116
		{
			yyVAL.node = appendNode(NodeOpSyntaxStatement, yyDollar[1].node)
		}
	case 23:
		yyDollar = yyS[yypt-2 : yypt+1]
//line macro.y:120
		{
			yyVAL.node = appendNodeTo(&yyDollar[1].node, yyDollar[2].node)
		}
	case 30:
		yyDollar = yyS[yypt-1 : yypt+1]
//line macro.y:127
		{
			yyVAL.node = newNode(NodeOpSyntaxKeywordElement, yyDollar[1].string)
		}
	case 31:
		yyDollar = yyS[yypt-4 : yypt+1]
//line macro.y:132
		{
			yyVAL.node = appendNode(NodeOpSyntaxVariableKeywordElement, newNode(NodeOpName, yyDollar[2].string), yyDollar[3].node)
		}
	case 32:
		yyDollar = yyS[yypt-3 : yypt+1]
//line macro.y:137
		{
			yyVAL.node = yyDollar[2].node
		}
	case 33:
		yyDollar = yyS[yypt-1 : yypt+1]
//line macro.y:142
		{
			yyVAL.node = appendNode(NodeOpSyntaxParameterListElement, yyDollar[1].node)
		}
	case 34:
		yyDollar = yyS[yypt-3 : yypt+1]
//line macro.y:146
		{
			yyVAL.node = appendNodeTo(&yyDollar[1].node, yyDollar[3].node)
		}
	case 35:
		yyDollar = yyS[yypt-3 : yypt+1]
//line macro.y:151
		{
			yyVAL.node = yyDollar[2].node
		}
	case 36:
		yyDollar = yyS[yypt-1 : yypt+1]
//line macro.y:156
		{
			yyVAL.node = appendNode(NodeOpSyntaxAttributeListElement, yyDollar[1].node)
		}
	case 37:
		yyDollar = yyS[yypt-3 : yypt+1]
//line macro.y:160
		{
			yyVAL.node = appendNodeTo(&yyDollar[1].node, yyDollar[3].node)
		}
	case 38:
		yyDollar = yyS[yypt-1 : yypt+1]
//line macro.y:165
		{
			yyVAL.node = newNode(NodeOpName, yyDollar[1].string)
		}
	case 39:
		yyDollar = yyS[yypt-2 : yypt+1]
//line macro.y:169
		{
			yyVAL.node = newNode(NodeOpValue, yyDollar[1].string, yyDollar[2].node)
		}
	case 40:
		yyDollar = yyS[yypt-6 : yypt+1]
//line macro.y:174
		{
			yyVAL.node = yyDollar[4].node
		}
	case 41:
		yyDollar = yyS[yypt-1 : yypt+1]
//line macro.y:179
		{
			yyVAL.node = appendNode(NodeOpSyntaxArgumentListElement, yyDollar[1].node)
		}
	case 42:
		yyDollar = yyS[yypt-3 : yypt+1]
//line macro.y:183
		{
			yyVAL.node = appendNodeTo(&yyDollar[1].node, yyDollar[3].node)
		}
	case 43:
		yyDollar = yyS[yypt-2 : yypt+1]
//line macro.y:188
		{
			yyVAL.node = newNode(NodeOpSyntaxCodeBlockElement, nil)
		}
	case 44:
		yyDollar = yyS[yypt-3 : yypt+1]
//line macro.y:192
		{
			yyVAL.node = newNode(NodeOpSyntaxCodeBlockElement, nil, yyDollar[2].node)
		}
	case 45:
		yyDollar = yyS[yypt-1 : yypt+1]
//line macro.y:197
		{
			yyVAL.node = newNode(NodeOpTypeDef, yyDollar[1].string)
		}
	case 46:
		yyDollar = yyS[yypt-4 : yypt+1]
//line macro.y:201
		{
			yyVAL.node = newNode(NodeOpTypeDef, yyDollar[1].string, yyDollar[3].node)
		}
	}
	goto yystack /* stack new state and value */
}
