// Code generated by goyacc -o logi.go logi.y. DO NOT EDIT.

//line logi.y:2
package logi

import __yyfmt__ "fmt"

//line logi.y:2

import (
	"github.com/tislib/logi/pkg/parser/lexer"
)

//line logi.y:10
type yySymType struct {
	yys      int
	node     yaccNode
	bool     bool
	number   interface{}
	string   string
	token    lexer.Token
	location lexer.Location
}

const token_number = 57346
const token_string = 57347
const token_identifier = 57348
const token_bool = 57349
const DefinitionKeyword = 57350
const SyntaxKeyword = 57351
const FuncKeyword = 57352
const BracketOpen = 57353
const BracketClose = 57354
const BraceOpen = 57355
const BraceClose = 57356
const Comma = 57357
const Colon = 57358
const Semicolon = 57359
const Equal = 57360
const GreaterThan = 57361
const LessThan = 57362
const Dot = 57363
const Arrow = 57364
const ParenOpen = 57365
const ParenClose = 57366
const Eol = 57367
const Plus = 57368
const Minus = 57369
const Star = 57370
const Slash = 57371
const Percent = 57372
const Exclamation = 57373
const And = 57374
const Or = 57375
const Xor = 57376

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"token_number",
	"token_string",
	"token_identifier",
	"token_bool",
	"DefinitionKeyword",
	"SyntaxKeyword",
	"FuncKeyword",
	"BracketOpen",
	"BracketClose",
	"BraceOpen",
	"BraceClose",
	"Comma",
	"Colon",
	"Semicolon",
	"Equal",
	"GreaterThan",
	"LessThan",
	"Dot",
	"Arrow",
	"ParenOpen",
	"ParenClose",
	"Eol",
	"Plus",
	"Minus",
	"Star",
	"Slash",
	"Percent",
	"Exclamation",
	"And",
	"Or",
	"Xor",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line logi.y:397

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 182

var yyAct = [...]uint8{
	3, 18, 7, 9, 87, 10, 33, 119, 49, 12,
	17, 84, 67, 46, 47, 15, 20, 37, 39, 40,
	138, 105, 5, 68, 96, 100, 90, 38, 130, 113,
	5, 5, 42, 82, 79, 78, 5, 58, 112, 6,
	40, 71, 72, 73, 74, 75, 76, 77, 80, 81,
	66, 64, 99, 62, 106, 98, 69, 60, 5, 65,
	63, 115, 89, 101, 40, 91, 102, 92, 117, 29,
	28, 27, 30, 68, 59, 14, 31, 94, 36, 97,
	55, 54, 48, 56, 139, 35, 107, 104, 34, 57,
	41, 108, 29, 28, 27, 30, 69, 85, 110, 31,
	44, 36, 103, 11, 32, 109, 118, 111, 35, 114,
	132, 34, 1, 124, 116, 13, 70, 29, 28, 128,
	30, 93, 129, 131, 2, 135, 8, 133, 134, 125,
	40, 121, 120, 123, 122, 86, 137, 23, 127, 140,
	126, 124, 136, 29, 28, 27, 30, 124, 141, 51,
	31, 50, 36, 53, 29, 88, 27, 30, 52, 35,
	45, 31, 34, 36, 5, 55, 54, 95, 56, 24,
	35, 43, 26, 34, 83, 25, 22, 61, 21, 19,
	16, 4,
}

var yyPact = [...]int16{
	33, 33, -3, -1000, -3, -1000, 97, -1000, -3, -1000,
	62, -1000, -1000, -1000, -3, 88, 139, 65, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -3, -1000, -1000, 76, 78, -3, 60, 65, -1000,
	-1000, -1000, 88, 36, -1000, 35, -1000, -1000, 50, 15,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, 91, 150, -1000,
	-1000, 11, 88, -1000, -3, -1000, -3, -1000, 161, 4,
	161, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 37, 34,
	-1000, -1000, 7, 51, -1000, 113, 6, -1000, 38, 74,
	-3, 92, 161, 14, 15, 0, 90, 15, -1000, -1000,
	-1000, 42, 91, -1000, 54, -3, 127, -1000, 88, -1000,
	90, -1000, -1000, 161, 9, -1000, -1000, -1000, 105, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -3, -3, 88, 15,
	-1000, -1000, 38, 105, 127, 5, -1000, 72, -3, -1000,
	127, -1000,
}

var yyPgo = [...]uint8{
	0, 12, 124, 181, 104, 180, 10, 1, 179, 178,
	177, 176, 16, 175, 174, 11, 172, 171, 13, 169,
	160, 14, 8, 158, 153, 151, 149, 137, 6, 135,
	4, 129, 7, 125, 121, 116, 112, 0, 18,
}

var yyR1 = [...]int8{
	0, 37, 37, 38, 36, 36, 36, 36, 36, 2,
	3, 4, 5, 5, 6, 6, 7, 7, 7, 7,
	7, 7, 7, 7, 8, 12, 12, 12, 9, 10,
	10, 10, 11, 27, 28, 29, 29, 29, 30, 32,
	32, 32, 32, 32, 32, 31, 33, 33, 33, 13,
	14, 14, 15, 15, 16, 16, 17, 17, 18, 19,
	19, 20, 20, 21, 1, 1, 22, 22, 22, 22,
	23, 23, 23, 24, 35, 35, 35, 35, 35, 35,
	35, 35, 35, 35, 35, 35, 35, 35, 25, 26,
	34, 34, 34,
}

var yyR2 = [...]int8{
	0, 1, 0, 1, 2, 2, 1, 3, 0, 3,
	2, 5, 2, 3, 1, 2, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 5, 1,
	4, 0, 1, 1, 5, 1, 4, 0, 3, 1,
	1, 1, 1, 1, 1, 5, 1, 4, 0, 5,
	1, 3, 1, 2, 3, 2, 1, 4, 2, 3,
	2, 1, 4, 1, 1, 4, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 2, 2, 2, 3, 4,
	1, 3, 0,
}

var yyChk = [...]int16{
	-1000, -36, -2, -37, -3, 25, 6, -37, -2, -37,
	-37, 6, -37, -4, 13, -37, -5, -6, -7, -8,
	-12, -9, -11, -27, -19, -13, -16, 6, 5, 4,
	7, 11, -4, -28, 23, 20, 13, -37, -6, -38,
	-7, 25, -37, -17, 24, -20, -18, -21, 6, -22,
	-25, -26, -23, -24, 5, 4, 7, 11, -37, 14,
	-38, -10, -6, 24, 15, 24, 15, -1, 23, 6,
	-35, 26, 27, 28, 29, 30, 31, 32, 20, 19,
	33, 34, 18, -14, -15, 6, -29, -30, 5, -37,
	15, -37, -37, -34, -22, 6, 20, -22, 18, 18,
	18, 12, 15, -12, -37, 15, 16, 12, -37, -18,
	6, -21, 24, 15, -1, 19, -15, 14, -37, -32,
	5, 4, 7, 6, -28, -31, 13, 11, -6, -22,
	19, -30, 5, -37, -37, -33, -32, -37, 15, 12,
	-37, -32,
}

var yyDef = [...]int8{
	2, -2, 2, 6, 2, 1, 0, 5, 2, 4,
	0, 10, 7, 9, 2, 0, 2, 0, 14, 16,
	17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
	27, 2, 32, 33, 0, 0, 2, 0, 0, 12,
	15, 3, 31, 0, 55, 0, 56, 61, 73, 63,
	66, 67, 68, 69, 70, 71, 72, 0, 37, 11,
	13, 2, 29, 54, 2, 59, 2, 58, 92, 64,
	0, 74, 75, 76, 77, 78, 79, 80, 81, 82,
	83, 84, 0, 0, 50, 52, 2, 35, 25, 0,
	2, 0, 0, 0, 90, 73, 0, 88, 87, 86,
	85, 0, 0, 53, 0, 2, 0, 28, 0, 57,
	0, 62, 89, 0, 0, 49, 51, 34, 0, 38,
	39, 40, 41, 42, 43, 44, 2, 2, 30, 91,
	65, 36, 0, 37, 48, 2, 46, 0, 2, 45,
	0, 47,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 4:
		yyDollar = yyS[yypt-2 : yypt+1]
//line logi.y:51
		{
			registerRootNode(yylex, yyDollar[1].node)
		}
	case 7:
		yyDollar = yyS[yypt-3 : yypt+1]
//line logi.y:56
		{
			registerRootNode(yylex, yyDollar[2].node)
		}
	case 9:
		yyDollar = yyS[yypt-3 : yypt+1]
//line logi.y:62
		{
			yyVAL.node = appendNode(NodeOpDefinition, yyDollar[1].node, yyDollar[3].node)
		}
	case 10:
		yyDollar = yyS[yypt-2 : yypt+1]
//line logi.y:67
		{
			yyVAL.node = appendNode(NodeOpSignature, newNode(NodeOpMacro, yyDollar[1].string, yyDollar[1].token, yyDollar[1].location), newNode(NodeOpName, yyDollar[2].string, yyDollar[2].token, yyDollar[2].location))
		}
	case 11:
		yyDollar = yyS[yypt-5 : yypt+1]
//line logi.y:74
		{
			yyVAL.node = appendNode(NodeOpBody, yyDollar[3].node)
		}
	case 12:
		yyDollar = yyS[yypt-2 : yypt+1]
//line logi.y:79
		{
			yyVAL.node = appendNode(NodeOpStatements, yyDollar[1].node)
		}
	case 13:
		yyDollar = yyS[yypt-3 : yypt+1]
//line logi.y:83
		{
			yyVAL.node = appendNodeTo(&yyDollar[1].node, yyDollar[2].node)
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:88
		{
			yyVAL.node = appendNode(NodeOpStatement, yyDollar[1].node)
		}
	case 15:
		yyDollar = yyS[yypt-2 : yypt+1]
//line logi.y:92
		{
			yyVAL.node = appendNodeTo(&yyDollar[1].node, yyDollar[2].node)
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:99
		{
			yyVAL.node = newNode(NodeOpIdentifier, yyDollar[1].string, yyDollar[1].token, yyDollar[1].location)
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:104
		{
			yyVAL.node = newNode(NodeOpValue, yyDollar[1].string, yyDollar[1].token, yyDollar[1].location)
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:108
		{
			yyVAL.node = newNode(NodeOpValue, yyDollar[1].number, yyDollar[1].token, yyDollar[1].location)
		}
	case 27:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:112
		{
			yyVAL.node = newNode(NodeOpValue, yyDollar[1].bool, yyDollar[1].token, yyDollar[1].location)
		}
	case 28:
		yyDollar = yyS[yypt-5 : yypt+1]
//line logi.y:117
		{
			yyVAL.node = yyDollar[3].node
		}
	case 29:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:122
		{
			yyVAL.node = appendNode(NodeOpArray, yyDollar[1].node)
		}
	case 30:
		yyDollar = yyS[yypt-4 : yypt+1]
//line logi.y:126
		{
			yyVAL.node = appendNodeTo(&yyDollar[1].node, yyDollar[4].node)
		}
	case 31:
		yyDollar = yyS[yypt-0 : yypt+1]
//line logi.y:130
		{
			yyVAL.node = appendNode(NodeOpArray)
		}
	case 32:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:135
		{
			yyVAL.node = appendNode(NodeOpStruct, yyDollar[1].node)
		}
	case 33:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:140
		{
			yyVAL.node = yyDollar[1].node
		}
	case 34:
		yyDollar = yyS[yypt-5 : yypt+1]
//line logi.y:145
		{
			yyVAL.node = yyDollar[3].node
		}
	case 35:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:150
		{
			yyVAL.node = appendNode(NodeOpJsonObject, yyDollar[1].node)
		}
	case 36:
		yyDollar = yyS[yypt-4 : yypt+1]
//line logi.y:153
		{
			yyVAL.node = appendNodeTo(&yyDollar[1].node, yyDollar[4].node)
		}
	case 37:
		yyDollar = yyS[yypt-0 : yypt+1]
//line logi.y:156
		{
			yyVAL.node = appendNode(NodeOpJsonObject)
		}
	case 38:
		yyDollar = yyS[yypt-3 : yypt+1]
//line logi.y:161
		{
			yyVAL.node = newNode(NodeOpJsonObjectItem, yyDollar[1].string, yyDollar[1].token, yyDollar[1].location, yyDollar[3].node)
		}
	case 39:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:166
		{
			yyVAL.node = newNode(NodeOpJsonObjectItemValue, yyDollar[1].string, yyDollar[1].token, yyDollar[1].location)
		}
	case 40:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:169
		{
			yyVAL.node = newNode(NodeOpJsonObjectItemValue, yyDollar[1].number, yyDollar[1].token, yyDollar[1].location)
		}
	case 41:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:172
		{
			yyVAL.node = newNode(NodeOpJsonObjectItemValue, yyDollar[1].bool, yyDollar[1].token, yyDollar[1].location)
		}
	case 42:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:175
		{
			yyVAL.node = newNode(NodeOpJsonIdentifier, yyDollar[1].string, yyDollar[1].token, yyDollar[1].location)
		}
	case 43:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:178
		{
			yyVAL.node = yyDollar[1].node
		}
	case 44:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:181
		{
			yyVAL.node = yyDollar[1].node
		}
	case 45:
		yyDollar = yyS[yypt-5 : yypt+1]
//line logi.y:186
		{
			yyVAL.node = yyDollar[3].node
		}
	case 46:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:191
		{
			yyVAL.node = appendNode(NodeOpJsonArray, yyDollar[1].node)
		}
	case 47:
		yyDollar = yyS[yypt-4 : yypt+1]
//line logi.y:194
		{
			yyVAL.node = appendNodeTo(&yyDollar[1].node, yyDollar[4].node)
		}
	case 48:
		yyDollar = yyS[yypt-0 : yypt+1]
//line logi.y:197
		{
			yyVAL.node = appendNode(NodeOpJsonArray)
		}
	case 49:
		yyDollar = yyS[yypt-5 : yypt+1]
//line logi.y:203
		{
			yyVAL.node = yyDollar[3].node
		}
	case 50:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:208
		{
			yyVAL.node = appendNode(NodeOpAttributeList, yyDollar[1].node)
		}
	case 51:
		yyDollar = yyS[yypt-3 : yypt+1]
//line logi.y:212
		{
			yyVAL.node = appendNodeTo(&yyDollar[1].node, yyDollar[3].node)
		}
	case 52:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:217
		{
			yyVAL.node = newNode(NodeOpAttribute, yyDollar[1].string, yyDollar[1].token, yyDollar[1].location)
		}
	case 53:
		yyDollar = yyS[yypt-2 : yypt+1]
//line logi.y:221
		{
			yyVAL.node = newNode(NodeOpAttribute, yyDollar[1].string, yyDollar[1].token, yyDollar[1].location, yyDollar[2].node)
		}
	case 54:
		yyDollar = yyS[yypt-3 : yypt+1]
//line logi.y:226
		{
			yyVAL.node = yyDollar[2].node
		}
	case 55:
		yyDollar = yyS[yypt-2 : yypt+1]
//line logi.y:230
		{
			yyVAL.node = appendNode(NodeOpArgumentList)
		}
	case 56:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:235
		{
			yyVAL.node = appendNode(NodeOpArgumentList, yyDollar[1].node)
		}
	case 57:
		yyDollar = yyS[yypt-4 : yypt+1]
//line logi.y:239
		{
			yyVAL.node = appendNodeTo(&yyDollar[1].node, yyDollar[4].node)
		}
	case 58:
		yyDollar = yyS[yypt-2 : yypt+1]
//line logi.y:244
		{
			yyVAL.node = newNode(NodeOpArgument, yyDollar[1].string, yyDollar[1].token, yyDollar[1].location, yyDollar[2].node)
		}
	case 59:
		yyDollar = yyS[yypt-3 : yypt+1]
//line logi.y:249
		{
			yyVAL.node = yyDollar[2].node
		}
	case 60:
		yyDollar = yyS[yypt-2 : yypt+1]
//line logi.y:253
		{
			yyVAL.node = appendNode(NodeOpParameterList)
		}
	case 61:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:258
		{
			yyVAL.node = appendNode(NodeOpParameterList, yyDollar[1].node)
		}
	case 62:
		yyDollar = yyS[yypt-4 : yypt+1]
//line logi.y:262
		{
			yyVAL.node = appendNodeTo(&yyDollar[1].node, yyDollar[4].node)
		}
	case 63:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:267
		{
			yyVAL.node = yyDollar[1].node
		}
	case 64:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:273
		{
			yyVAL.node = newNode(NodeOpTypeDef, yyDollar[1].string, yyDollar[1].token, yyDollar[1].location)
		}
	case 65:
		yyDollar = yyS[yypt-4 : yypt+1]
//line logi.y:277
		{
			yyVAL.node = newNode(NodeOpTypeDef, yyDollar[1].string, yyDollar[1].token, yyDollar[1].location, yyDollar[3].node)
		}
	case 66:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:284
		{
			yyVAL.node = appendNode(NodeOpExpression, yyDollar[1].node)
		}
	case 67:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:288
		{
			yyVAL.node = appendNode(NodeOpExpression, yyDollar[1].node)
		}
	case 68:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:292
		{
			yyVAL.node = appendNode(NodeOpExpression, yyDollar[1].node)
		}
	case 69:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:296
		{
			yyVAL.node = appendNode(NodeOpExpression, yyDollar[1].node)
		}
	case 70:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:301
		{
			yyVAL.node = newNode(NodeOpLiteral, yyDollar[1].string, yyDollar[1].token, yyDollar[1].location)
		}
	case 71:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:305
		{
			yyVAL.node = newNode(NodeOpLiteral, yyDollar[1].number, yyDollar[1].token, yyDollar[1].location)
		}
	case 72:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:309
		{
			yyVAL.node = newNode(NodeOpLiteral, yyDollar[1].bool, yyDollar[1].token, yyDollar[1].location)
		}
	case 73:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:314
		{
			yyVAL.node = newNode(NodeOpVariable, yyDollar[1].string, yyDollar[1].token, yyDollar[1].location)
		}
	case 74:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:318
		{
			yyVAL.string = "+"
		}
	case 75:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:321
		{
			yyVAL.string = "-"
		}
	case 76:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:325
		{
			yyVAL.string = "*"
		}
	case 77:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:329
		{
			yyVAL.string = "/"
		}
	case 78:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:333
		{
			yyVAL.string = "%"
		}
	case 79:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:337
		{
			yyVAL.string = "!"
		}
	case 80:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:341
		{
			yyVAL.string = "&&"
		}
	case 81:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:345
		{
			yyVAL.string = "<"
		}
	case 82:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:349
		{
			yyVAL.string = ">"
		}
	case 83:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:353
		{
			yyVAL.string = "||"
		}
	case 84:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:357
		{
			yyVAL.string = "^"
		}
	case 85:
		yyDollar = yyS[yypt-2 : yypt+1]
//line logi.y:361
		{
			yyVAL.string = "=="
		}
	case 86:
		yyDollar = yyS[yypt-2 : yypt+1]
//line logi.y:365
		{
			yyVAL.string = ">="
		}
	case 87:
		yyDollar = yyS[yypt-2 : yypt+1]
//line logi.y:369
		{
			yyVAL.string = "<="
		}
	case 88:
		yyDollar = yyS[yypt-3 : yypt+1]
//line logi.y:374
		{
			yyVAL.node = appendNode(NodeOpBinaryExpression, yyDollar[1].node, yyDollar[3].node, newNode(NodeOpOperator, yyDollar[2].string, yyDollar[2].token, yyDollar[2].location))
		}
	case 89:
		yyDollar = yyS[yypt-4 : yypt+1]
//line logi.y:379
		{
			yyVAL.node = newNode(NodeOpFunctionCall, yyDollar[1].string, yyDollar[1].token, yyDollar[1].location, yyDollar[3].node)
		}
	case 90:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:384
		{
			yyVAL.node = appendNode(NodeOpFunctionParams, yyDollar[1].node)
		}
	case 91:
		yyDollar = yyS[yypt-3 : yypt+1]
//line logi.y:388
		{
			yyVAL.node = appendNodeTo(&yyDollar[1].node, yyDollar[3].node)
		}
	case 92:
		yyDollar = yyS[yypt-0 : yypt+1]
//line logi.y:392
		{
			yyVAL.node = appendNode(NodeOpFunctionParams)
		}
	}
	goto yystack /* stack new state and value */
}
