// Code generated by goyacc -o logi.go logi.y. DO NOT EDIT.

//line logi.y:2
package logi

import __yyfmt__ "fmt"

//line logi.y:2

import ()

//line logi.y:9
type yySymType struct {
	yys    int
	node   yaccNode
	bool   bool
	number interface{}
	string string
}

const token_number = 57346
const token_string = 57347
const token_identifier = 57348
const token_bool = 57349
const DefinitionKeyword = 57350
const SyntaxKeyword = 57351
const FuncKeyword = 57352
const BracketOpen = 57353
const BracketClose = 57354
const BraceOpen = 57355
const BraceClose = 57356
const Comma = 57357
const Colon = 57358
const Semicolon = 57359
const Equal = 57360
const GreaterThan = 57361
const LessThan = 57362
const Dot = 57363
const Arrow = 57364
const ParenOpen = 57365
const ParenClose = 57366
const Eol = 57367
const IfKeyword = 57368
const ElseKeyword = 57369
const ReturnKeyword = 57370
const SwitchKeyword = 57371
const CaseKeyword = 57372
const VarKeyword = 57373
const Plus = 57374
const Minus = 57375
const Star = 57376
const Slash = 57377
const Percent = 57378
const Exclamation = 57379
const And = 57380
const Or = 57381
const Xor = 57382

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"token_number",
	"token_string",
	"token_identifier",
	"token_bool",
	"DefinitionKeyword",
	"SyntaxKeyword",
	"FuncKeyword",
	"BracketOpen",
	"BracketClose",
	"BraceOpen",
	"BraceClose",
	"Comma",
	"Colon",
	"Semicolon",
	"Equal",
	"GreaterThan",
	"LessThan",
	"Dot",
	"Arrow",
	"ParenOpen",
	"ParenClose",
	"Eol",
	"IfKeyword",
	"ElseKeyword",
	"ReturnKeyword",
	"SwitchKeyword",
	"CaseKeyword",
	"VarKeyword",
	"Plus",
	"Minus",
	"Star",
	"Slash",
	"Percent",
	"Exclamation",
	"And",
	"Or",
	"Xor",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line logi.y:330

//		entity User {
//	  		id int [primary, autoincrement]
//	 		name string [required, default "John Doe"]
//	  	}
//
//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 64,
	25, 50,
	-2, 60,
}

const yyPrivate = 57344

const yyLast = 199

var yyAct = [...]int8{
	38, 47, 65, 51, 55, 4, 99, 9, 12, 13,
	58, 15, 29, 32, 35, 33, 18, 19, 124, 116,
	119, 80, 53, 25, 7, 14, 96, 24, 77, 118,
	115, 30, 44, 74, 73, 69, 75, 49, 89, 90,
	91, 92, 93, 94, 95, 50, 105, 78, 52, 28,
	102, 64, 97, 26, 79, 21, 114, 14, 14, 76,
	96, 8, 86, 84, 64, 6, 52, 14, 85, 98,
	100, 83, 89, 90, 91, 92, 93, 94, 95, 103,
	7, 23, 117, 81, 46, 37, 82, 104, 26, 106,
	107, 108, 87, 45, 96, 74, 73, 69, 75, 110,
	109, 48, 22, 111, 56, 113, 89, 90, 91, 92,
	93, 94, 95, 101, 96, 30, 120, 121, 41, 40,
	122, 42, 123, 17, 16, 125, 89, 90, 91, 92,
	93, 94, 95, 74, 73, 69, 75, 74, 73, 69,
	75, 3, 1, 11, 41, 40, 39, 42, 2, 88,
	10, 43, 112, 26, 7, 66, 70, 67, 14, 66,
	68, 67, 72, 23, 68, 53, 41, 40, 39, 42,
	71, 59, 63, 43, 62, 26, 61, 41, 40, 39,
	42, 60, 57, 27, 43, 23, 26, 7, 54, 36,
	34, 31, 20, 5, 0, 0, 23, 0, 14,
}

var yyPact = [...]int16{
	55, 55, -1, -1, 0, -1, 118, -1000, 117, 0,
	-1, -1, 0, 0, -1000, 42, 58, -1000, 0, 0,
	-1000, -1, 75, 25, 173, -1000, -1, 69, -1000, -1000,
	95, 162, 140, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, 98, 133, -1000, 109, -1000, 8, 33,
	140, -4, -1000, -1000, 71, -1000, 114, 129, -3, -1000,
	-1000, -1000, -1000, -1000, -1000, 74, 29, 91, 107, 27,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, 95, -1000, -4,
	-1000, -1000, 98, -1000, 32, -3, -4, 91, 91, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, 91, 40, -1000,
	94, 95, 91, 37, -1000, -1000, -4, 94, 94, 6,
	-8, 64, 5, 94, -1000, 75, 75, 91, -1000, 91,
	-9, -1000, 94, 94, 75, -1000,
}

var yyPgo = [...]uint8{
	0, 1, 148, 193, 192, 191, 13, 15, 190, 14,
	189, 188, 4, 85, 183, 12, 0, 182, 10, 181,
	176, 174, 172, 171, 2, 170, 162, 156, 6, 152,
	141, 149, 142, 5, 3,
}

var yyR1 = [...]int8{
	0, 33, 33, 33, 34, 34, 32, 32, 32, 32,
	32, 32, 32, 2, 3, 4, 5, 5, 6, 6,
	7, 7, 7, 7, 7, 8, 9, 9, 9, 10,
	11, 11, 12, 12, 13, 13, 14, 14, 15, 1,
	1, 16, 17, 17, 17, 18, 18, 18, 18, 18,
	23, 19, 20, 20, 20, 20, 21, 22, 22, 24,
	24, 24, 24, 25, 25, 25, 26, 31, 31, 31,
	31, 31, 31, 31, 31, 27, 28, 29, 29, 29,
	30,
}

var yyR2 = [...]int8{
	0, 1, 2, 0, 1, 2, 2, 2, 2, 1,
	3, 3, 0, 3, 2, 5, 2, 3, 1, 2,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 3,
	1, 3, 1, 2, 3, 2, 1, 3, 2, 1,
	4, 5, 2, 3, 0, 1, 1, 1, 1, 1,
	1, 3, 5, 7, 3, 5, 2, 3, 5, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 3, 4, 1, 3, 0,
	4,
}

var yyChk = [...]int16{
	-1000, -32, -2, -30, -33, -3, 10, 25, 6, -33,
	-2, -30, -33, -33, 25, -33, 6, 6, -33, -33,
	-4, 13, -13, 23, -33, -16, 13, -14, 24, -15,
	6, -5, -6, -7, -8, -9, -10, -13, -16, 6,
	5, 4, 7, 11, -33, 24, 15, -1, 6, -33,
	-6, -34, -7, 25, -11, -12, 6, -17, -18, -23,
	-19, -20, -21, -22, -28, -24, 26, 28, 31, 6,
	-27, -25, -26, 5, 4, 7, -15, 20, 14, -34,
	25, 12, 15, -9, -33, -18, -34, 18, -31, 32,
	33, 34, 35, 36, 37, 38, 20, 23, -24, -28,
	-24, 6, 23, -1, -12, 14, -34, -24, -24, -24,
	-16, -1, -29, -24, 19, 24, 27, 18, 24, 15,
	-16, -16, -24, -24, 27, -16,
}

var yyDef = [...]int8{
	3, -2, 3, 3, 9, 3, 0, 1, 0, 8,
	3, 3, 6, 7, 2, 0, 0, 14, 10, 11,
	13, 3, 0, 0, 0, 80, 3, 0, 35, 36,
	0, 3, 0, 18, 20, 21, 22, 23, 24, 25,
	26, 27, 28, 0, 44, 34, 0, 38, 39, 0,
	0, 16, 19, 4, 0, 30, 32, 3, 0, 45,
	46, 47, 48, 49, -2, 0, 0, 0, 0, 66,
	59, 61, 62, 63, 64, 65, 37, 0, 15, 17,
	5, 29, 0, 33, 0, 0, 42, 0, 0, 67,
	68, 69, 70, 71, 72, 73, 74, 0, 0, 60,
	56, 0, 79, 0, 31, 41, 43, 51, 75, 0,
	54, 57, 0, 77, 40, 0, 0, 0, 76, 0,
	52, 55, 58, 78, 0, 53,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 6:
		yyDollar = yyS[yypt-2 : yypt+1]
//line logi.y:52
		{
			registerRootNode(yylex, yyDollar[1].node)
		}
	case 7:
		yyDollar = yyS[yypt-2 : yypt+1]
//line logi.y:55
		{
			registerRootNode(yylex, yyDollar[1].node)
		}
	case 10:
		yyDollar = yyS[yypt-3 : yypt+1]
//line logi.y:60
		{
			registerRootNode(yylex, yyDollar[2].node)
		}
	case 11:
		yyDollar = yyS[yypt-3 : yypt+1]
//line logi.y:63
		{
			registerRootNode(yylex, yyDollar[2].node)
		}
	case 13:
		yyDollar = yyS[yypt-3 : yypt+1]
//line logi.y:69
		{
			yyVAL.node = appendNode(NodeOpDefinition, yyDollar[1].node, yyDollar[3].node)
		}
	case 14:
		yyDollar = yyS[yypt-2 : yypt+1]
//line logi.y:74
		{
			yyVAL.node = appendNode(NodeOpSignature, newNode(NodeOpMacro, yyDollar[1].string), newNode(NodeOpName, yyDollar[2].string))
		}
	case 15:
		yyDollar = yyS[yypt-5 : yypt+1]
//line logi.y:81
		{
			yyVAL.node = appendNode(NodeOpBody, yyDollar[3].node)
		}
	case 16:
		yyDollar = yyS[yypt-2 : yypt+1]
//line logi.y:86
		{
			yyVAL.node = appendNode(NodeOpStatements, yyDollar[1].node)
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
//line logi.y:90
		{
			yyVAL.node = appendNodeTo(&yyDollar[1].node, yyDollar[2].node)
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:95
		{
			yyVAL.node = appendNode(NodeOpStatement, yyDollar[1].node)
		}
	case 19:
		yyDollar = yyS[yypt-2 : yypt+1]
//line logi.y:99
		{
			yyVAL.node = appendNodeTo(&yyDollar[1].node, yyDollar[2].node)
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:106
		{
			yyVAL.node = newNode(NodeOpIdentifier, yyDollar[1].string)
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:111
		{
			yyVAL.node = newNode(NodeOpValue, yyDollar[1].string)
		}
	case 27:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:115
		{
			yyVAL.node = newNode(NodeOpValue, yyDollar[1].number)
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:119
		{
			yyVAL.node = newNode(NodeOpValue, yyDollar[1].bool)
		}
	case 29:
		yyDollar = yyS[yypt-3 : yypt+1]
//line logi.y:124
		{
			yyVAL.node = yyDollar[2].node
		}
	case 30:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:129
		{
			yyVAL.node = appendNode(NodeOpAttributeList, yyDollar[1].node)
		}
	case 31:
		yyDollar = yyS[yypt-3 : yypt+1]
//line logi.y:133
		{
			yyVAL.node = appendNodeTo(&yyDollar[1].node, yyDollar[3].node)
		}
	case 32:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:138
		{
			yyVAL.node = newNode(NodeOpAttribute, yyDollar[1].string)
		}
	case 33:
		yyDollar = yyS[yypt-2 : yypt+1]
//line logi.y:142
		{
			yyVAL.node = newNode(NodeOpAttribute, yyDollar[1].string, yyDollar[2].node)
		}
	case 34:
		yyDollar = yyS[yypt-3 : yypt+1]
//line logi.y:147
		{
			yyVAL.node = yyDollar[2].node
		}
	case 35:
		yyDollar = yyS[yypt-2 : yypt+1]
//line logi.y:151
		{
			yyVAL.node = appendNode(NodeOpArgumentList)
		}
	case 36:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:156
		{
			yyVAL.node = appendNode(NodeOpArgumentList, yyDollar[1].node)
		}
	case 37:
		yyDollar = yyS[yypt-3 : yypt+1]
//line logi.y:160
		{
			yyVAL.node = appendNodeTo(&yyDollar[1].node, yyDollar[3].node)
		}
	case 38:
		yyDollar = yyS[yypt-2 : yypt+1]
//line logi.y:165
		{
			yyVAL.node = newNode(NodeOpArgument, yyDollar[1].string, yyDollar[2].node)
		}
	case 39:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:171
		{
			yyVAL.node = newNode(NodeOpTypeDef, yyDollar[1].string)
		}
	case 40:
		yyDollar = yyS[yypt-4 : yypt+1]
//line logi.y:175
		{
			yyVAL.node = newNode(NodeOpTypeDef, yyDollar[1].string, yyDollar[3].node)
		}
	case 41:
		yyDollar = yyS[yypt-5 : yypt+1]
//line logi.y:183
		{
			yyVAL.node = appendNode(NodeOpCodeBlock, yyDollar[3].node)
		}
	case 42:
		yyDollar = yyS[yypt-2 : yypt+1]
//line logi.y:188
		{
			yyVAL.node = appendNode(NodeOpStatements, yyDollar[1].node)
		}
	case 43:
		yyDollar = yyS[yypt-3 : yypt+1]
//line logi.y:192
		{
			yyVAL.node = appendNodeTo(&yyDollar[1].node, yyDollar[2].node)
		}
	case 44:
		yyDollar = yyS[yypt-0 : yypt+1]
//line logi.y:196
		{
			yyVAL.node = appendNode(NodeOpStatements)
		}
	case 50:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:205
		{
			yyVAL.node = appendNode(NodeOpFunctionCall, yyDollar[1].node)
		}
	case 51:
		yyDollar = yyS[yypt-3 : yypt+1]
//line logi.y:210
		{
			yyVAL.node = appendNode(NodeOpAssignment, yyDollar[1].node, yyDollar[3].node)
		}
	case 52:
		yyDollar = yyS[yypt-5 : yypt+1]
//line logi.y:215
		{
			yyVAL.node = appendNode(NodeOpIf, yyDollar[3].node, yyDollar[5].node)
		}
	case 53:
		yyDollar = yyS[yypt-7 : yypt+1]
//line logi.y:219
		{
			yyVAL.node = appendNode(NodeOpIfElse, yyDollar[3].node, yyDollar[5].node, yyDollar[7].node)
		}
	case 54:
		yyDollar = yyS[yypt-3 : yypt+1]
//line logi.y:223
		{
			yyVAL.node = appendNode(NodeOpIf, yyDollar[2].node, yyDollar[3].node)
		}
	case 55:
		yyDollar = yyS[yypt-5 : yypt+1]
//line logi.y:227
		{
			yyVAL.node = appendNode(NodeOpIfElse, yyDollar[2].node, yyDollar[3].node, yyDollar[5].node)
		}
	case 56:
		yyDollar = yyS[yypt-2 : yypt+1]
//line logi.y:232
		{
			yyVAL.node = appendNode(NodeOpReturn, yyDollar[2].node)
		}
	case 57:
		yyDollar = yyS[yypt-3 : yypt+1]
//line logi.y:237
		{
			yyVAL.node = appendNode(NodeOpVariableDeclaration, newNode(NodeOpName, yyDollar[2].string), yyDollar[3].node)
		}
	case 58:
		yyDollar = yyS[yypt-5 : yypt+1]
//line logi.y:241
		{
			yyVAL.node = appendNode(NodeOpVariableDeclaration, newNode(NodeOpName, yyDollar[2].string), yyDollar[3].node, yyDollar[5].node)
		}
	case 63:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:250
		{
			yyVAL.node = newNode(NodeOpLiteral, yyDollar[1].string)
		}
	case 64:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:254
		{
			yyVAL.node = newNode(NodeOpLiteral, yyDollar[1].number)
		}
	case 65:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:258
		{
			yyVAL.node = newNode(NodeOpLiteral, yyDollar[1].bool)
		}
	case 66:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:263
		{
			yyVAL.node = newNode(NodeOpVariable, yyDollar[1].string)
		}
	case 67:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:267
		{
			yyVAL.string = "+"
		}
	case 68:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:270
		{
			yyVAL.string = "-"
		}
	case 69:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:274
		{
			yyVAL.string = "*"
		}
	case 70:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:278
		{
			yyVAL.string = "/"
		}
	case 71:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:282
		{
			yyVAL.string = "%"
		}
	case 72:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:286
		{
			yyVAL.string = "!"
		}
	case 73:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:290
		{
			yyVAL.string = "&&"
		}
	case 74:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:294
		{
			yyVAL.string = "<"
		}
	case 75:
		yyDollar = yyS[yypt-3 : yypt+1]
//line logi.y:300
		{
			yyVAL.node = appendNode(NodeOpBinaryExpression, yyDollar[1].node, yyDollar[3].node, newNode(NodeOpOperator, yyDollar[2].string))
		}
	case 76:
		yyDollar = yyS[yypt-4 : yypt+1]
//line logi.y:305
		{
			yyVAL.node = newNode(NodeOpFunctionCall, yyDollar[1].string, yyDollar[3].node)
		}
	case 77:
		yyDollar = yyS[yypt-1 : yypt+1]
//line logi.y:310
		{
			yyVAL.node = appendNode(NodeOpFunctionParams, yyDollar[1].node)
		}
	case 78:
		yyDollar = yyS[yypt-3 : yypt+1]
//line logi.y:314
		{
			yyVAL.node = appendNodeTo(&yyDollar[1].node, yyDollar[3].node)
		}
	case 79:
		yyDollar = yyS[yypt-0 : yypt+1]
//line logi.y:318
		{
			yyVAL.node = appendNode(NodeOpFunctionParams)
		}
	case 80:
		yyDollar = yyS[yypt-4 : yypt+1]
//line logi.y:326
		{
			yyVAL.node = appendNode(NodeOpFunctionDefinition, newNode(NodeOpName, yyDollar[2].string), yyDollar[3].node, yyDollar[4].node)
		}
	}
	goto yystack /* stack new state and value */
}
