// Code generated by goyacc -o macro.go macro.y. DO NOT EDIT.

//line macro.y:2
package macro

import __yyfmt__ "fmt"

//line macro.y:2

import ()

//line macro.y:9
type yySymType struct {
	yys    int
	node   yaccNode
	bool   bool
	number interface{}
	string string
}

const token_number = 57346
const token_string = 57347
const token_identifier = 57348
const token_bool = 57349
const TypesKeyword = 57350
const SyntaxKeyword = 57351
const MacroKeyword = 57352
const BracketOpen = 57353
const BracketClose = 57354
const BraceOpen = 57355
const BraceClose = 57356
const Comma = 57357
const Colon = 57358
const Semicolon = 57359
const Equal = 57360
const GreaterThan = 57361
const LessThan = 57362
const Dash = 57363
const Dot = 57364
const Arrow = 57365
const ParenOpen = 57366
const ParenClose = 57367
const Eol = 57368

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"token_number",
	"token_string",
	"token_identifier",
	"token_bool",
	"TypesKeyword",
	"SyntaxKeyword",
	"MacroKeyword",
	"BracketOpen",
	"BracketClose",
	"BraceOpen",
	"BraceClose",
	"Comma",
	"Colon",
	"Semicolon",
	"Equal",
	"GreaterThan",
	"LessThan",
	"Dash",
	"Dot",
	"Arrow",
	"ParenOpen",
	"ParenClose",
	"Eol",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line macro.y:230

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 133

var yyAct = [...]int8{
	47, 71, 19, 86, 44, 63, 23, 43, 35, 36,
	59, 36, 52, 37, 21, 10, 28, 55, 3, 51,
	7, 9, 10, 11, 21, 10, 53, 13, 29, 5,
	54, 10, 20, 10, 16, 38, 15, 17, 42, 10,
	80, 24, 6, 41, 60, 30, 31, 58, 61, 10,
	79, 98, 39, 40, 20, 68, 56, 10, 5, 5,
	53, 75, 69, 61, 93, 74, 82, 53, 77, 95,
	89, 78, 96, 76, 33, 97, 73, 87, 85, 61,
	26, 90, 92, 88, 83, 52, 94, 84, 52, 64,
	55, 81, 51, 55, 72, 51, 64, 62, 99, 53,
	65, 18, 53, 54, 52, 5, 54, 12, 10, 55,
	2, 51, 8, 67, 1, 70, 50, 45, 53, 91,
	49, 66, 54, 48, 46, 25, 22, 34, 57, 32,
	27, 14, 4,
}

var yyPact = [...]int16{
	32, 32, 33, 13, 33, -1000, 101, 13, 33, 13,
	-1000, 23, -1000, 13, -1000, 33, 31, 95, 28, -2,
	-1000, -1000, 33, 67, 7, 28, 33, 33, 61, -12,
	5, -1, 28, 33, 3, 28, 98, 33, -12, 82,
	-4, 28, -12, 98, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, 83, -1000, 94, 40, 88, 13, 79, 6, -1000,
	-12, -1000, -1000, 59, 48, 90, 25, 80, -1000, 44,
	72, -1000, 90, -11, 6, -12, -1000, 90, 51, -1000,
	47, 47, 42, -1000, 88, -1000, -1000, -12, 50, -1000,
	-1000, 60, -1000, -1000, -1000, -1000, 26, 47, -1000, -1000,
}

var yyPgo = [...]uint8{
	0, 110, 132, 131, 130, 129, 128, 5, 127, 126,
	125, 8, 7, 4, 0, 124, 123, 121, 120, 119,
	117, 116, 115, 1, 114, 18, 2, 113,
}

var yyR1 = [...]int8{
	0, 25, 25, 25, 26, 26, 27, 24, 24, 24,
	24, 1, 2, 3, 9, 9, 10, 8, 8, 8,
	8, 11, 4, 4, 5, 6, 6, 6, 12, 12,
	13, 13, 13, 13, 13, 13, 15, 14, 16, 17,
	17, 21, 22, 22, 23, 23, 18, 19, 19, 20,
	20, 7, 7,
}

var yyR2 = [...]int8{
	0, 1, 2, 0, 1, 2, 3, 2, 2, 1,
	3, 3, 2, 11, 3, 0, 5, 2, 3, 0,
	0, 2, 3, 0, 5, 2, 3, 0, 1, 2,
	1, 1, 1, 1, 1, 1, 1, 4, 3, 1,
	3, 3, 1, 3, 1, 2, 6, 1, 3, 2,
	3, 1, 4,
}

var yyChk = [...]int16{
	-1000, -24, -1, -25, -2, 26, 10, -25, -1, -25,
	26, -25, 6, -25, -3, 13, -25, 6, 6, -26,
	26, 26, -9, 8, -25, -10, 13, -4, 9, -26,
	-25, -25, -5, 13, -8, -11, 6, 14, -26, -25,
	-25, -11, -26, -12, -13, -20, -15, -14, -16, -18,
	-21, 13, 6, 20, 24, 11, -25, -6, -12, 14,
	-26, -13, 14, -7, 6, 6, -17, -27, -14, 22,
	-22, -23, 6, -25, -12, -26, 14, 20, -7, 25,
	15, 11, 22, 12, 15, -7, 14, -26, -7, 19,
	-14, -19, -14, 22, -23, 19, 12, 15, 25, -14,
}

var yyDef = [...]int8{
	3, -2, 3, 9, 3, 1, 0, 8, 3, 7,
	2, 0, 12, 10, 11, 3, 0, 0, 0, 15,
	4, 5, 3, 0, 23, 0, 3, 3, 0, 14,
	19, 0, 0, 3, 3, 0, 0, 3, 22, 27,
	0, 0, 17, 21, 28, 30, 31, 32, 33, 34,
	35, 0, 36, 0, 0, 0, 13, 3, 0, 16,
	18, 29, 49, 0, 51, 0, 0, 0, 39, 0,
	0, 42, 44, 0, 0, 25, 50, 0, 0, 38,
	0, 0, 0, 41, 0, 45, 24, 26, 0, 37,
	40, 0, 47, 6, 43, 52, 0, 0, 46, 48,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 7:
		yyDollar = yyS[yypt-2 : yypt+1]
//line macro.y:49
		{
			registerRootNode(yylex, yyDollar[1].node)
		}
	case 10:
		yyDollar = yyS[yypt-3 : yypt+1]
//line macro.y:54
		{
			registerRootNode(yylex, yyDollar[2].node)
		}
	case 11:
		yyDollar = yyS[yypt-3 : yypt+1]
//line macro.y:60
		{
			yyVAL.node = appendNode(NodeOpMacro, yyDollar[1].node, yyDollar[3].node)
		}
	case 12:
		yyDollar = yyS[yypt-2 : yypt+1]
//line macro.y:65
		{
			yyVAL.node = appendNode(NodeOpSignature, newNode(NodeOpName, yyDollar[2].string))
		}
	case 13:
		yyDollar = yyS[yypt-11 : yypt+1]
//line macro.y:77
		{
			assertEqual(yylex, yyDollar[3].string, "kind", "First identifier in macro body must be 'kind'")
			yyVAL.node = appendNode(NodeOpBody, newNode(NodeOpKind, yyDollar[4].string), yyDollar[6].node, yyDollar[8].node)
		}
	case 14:
		yyDollar = yyS[yypt-3 : yypt+1]
//line macro.y:83
		{
			yyVAL.node = appendNode(NodeOpTypes, yyDollar[2].node)
		}
	case 15:
		yyDollar = yyS[yypt-0 : yypt+1]
//line macro.y:87
		{
			yyVAL.node = appendNode(NodeOpTypes)
		}
	case 16:
		yyDollar = yyS[yypt-5 : yypt+1]
//line macro.y:92
		{
			yyVAL.node = yyDollar[3].node
		}
	case 17:
		yyDollar = yyS[yypt-2 : yypt+1]
//line macro.y:96
		{
			yyVAL.node = appendNode(NodeOpBody, yyDollar[1].node)
		}
	case 18:
		yyDollar = yyS[yypt-3 : yypt+1]
//line macro.y:99
		{
			yyVAL.node = appendNodeTo(&yyDollar[1].node, yyDollar[2].node)
		}
	case 19:
		yyDollar = yyS[yypt-0 : yypt+1]
//line macro.y:102
		{
			yyVAL.node = appendNode(NodeOpBody)
		}
	case 20:
		yyDollar = yyS[yypt-0 : yypt+1]
//line macro.y:106
		{
			yyVAL.node = appendNode(NodeOpBody)
		}
	case 21:
		yyDollar = yyS[yypt-2 : yypt+1]
//line macro.y:111
		{
			yyVAL.node = appendNode(NodeOpTypesStatement, newNode(NodeOpName, yyDollar[1].string), yyDollar[2].node)
		}
	case 22:
		yyDollar = yyS[yypt-3 : yypt+1]
//line macro.y:116
		{
			yyVAL.node = appendNode(NodeOpSyntax, yyDollar[2].node)
		}
	case 23:
		yyDollar = yyS[yypt-0 : yypt+1]
//line macro.y:120
		{
			yyVAL.node = appendNode(NodeOpSyntax)
		}
	case 24:
		yyDollar = yyS[yypt-5 : yypt+1]
//line macro.y:126
		{
			yyVAL.node = yyDollar[3].node
		}
	case 25:
		yyDollar = yyS[yypt-2 : yypt+1]
//line macro.y:130
		{
			yyVAL.node = appendNode(NodeOpBody, yyDollar[1].node)
		}
	case 26:
		yyDollar = yyS[yypt-3 : yypt+1]
//line macro.y:133
		{
			yyVAL.node = appendNodeTo(&yyDollar[1].node, yyDollar[2].node)
		}
	case 27:
		yyDollar = yyS[yypt-0 : yypt+1]
//line macro.y:136
		{
			yyVAL.node = appendNode(NodeOpBody)
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
//line macro.y:141
		{
			yyVAL.node = appendNode(NodeOpSyntaxStatement, yyDollar[1].node)
		}
	case 29:
		yyDollar = yyS[yypt-2 : yypt+1]
//line macro.y:145
		{
			yyVAL.node = appendNodeTo(&yyDollar[1].node, yyDollar[2].node)
		}
	case 36:
		yyDollar = yyS[yypt-1 : yypt+1]
//line macro.y:152
		{
			yyVAL.node = newNode(NodeOpSyntaxKeywordElement, yyDollar[1].string)
		}
	case 37:
		yyDollar = yyS[yypt-4 : yypt+1]
//line macro.y:157
		{
			yyVAL.node = appendNode(NodeOpSyntaxVariableKeywordElement, newNode(NodeOpName, yyDollar[2].string), yyDollar[3].node)
		}
	case 38:
		yyDollar = yyS[yypt-3 : yypt+1]
//line macro.y:162
		{
			yyVAL.node = yyDollar[2].node
		}
	case 39:
		yyDollar = yyS[yypt-1 : yypt+1]
//line macro.y:167
		{
			yyVAL.node = appendNode(NodeOpSyntaxParameterListElement, yyDollar[1].node)
		}
	case 40:
		yyDollar = yyS[yypt-3 : yypt+1]
//line macro.y:171
		{
			yyVAL.node = appendNodeTo(&yyDollar[1].node, yyDollar[3].node)
		}
	case 41:
		yyDollar = yyS[yypt-3 : yypt+1]
//line macro.y:176
		{
			yyVAL.node = yyDollar[2].node
		}
	case 42:
		yyDollar = yyS[yypt-1 : yypt+1]
//line macro.y:181
		{
			yyVAL.node = appendNode(NodeOpSyntaxAttributeListElement, yyDollar[1].node)
		}
	case 43:
		yyDollar = yyS[yypt-3 : yypt+1]
//line macro.y:185
		{
			yyVAL.node = appendNodeTo(&yyDollar[1].node, yyDollar[3].node)
		}
	case 44:
		yyDollar = yyS[yypt-1 : yypt+1]
//line macro.y:190
		{
			yyVAL.node = newNode(NodeOpName, yyDollar[1].string)
		}
	case 45:
		yyDollar = yyS[yypt-2 : yypt+1]
//line macro.y:194
		{
			yyVAL.node = newNode(NodeOpValue, yyDollar[1].string, yyDollar[2].node)
		}
	case 46:
		yyDollar = yyS[yypt-6 : yypt+1]
//line macro.y:199
		{
			yyVAL.node = yyDollar[4].node
		}
	case 47:
		yyDollar = yyS[yypt-1 : yypt+1]
//line macro.y:204
		{
			yyVAL.node = appendNode(NodeOpSyntaxArgumentListElement, yyDollar[1].node)
		}
	case 48:
		yyDollar = yyS[yypt-3 : yypt+1]
//line macro.y:208
		{
			yyVAL.node = appendNodeTo(&yyDollar[1].node, yyDollar[3].node)
		}
	case 49:
		yyDollar = yyS[yypt-2 : yypt+1]
//line macro.y:213
		{
			yyVAL.node = newNode(NodeOpSyntaxCodeBlockElement, nil)
		}
	case 50:
		yyDollar = yyS[yypt-3 : yypt+1]
//line macro.y:217
		{
			yyVAL.node = newNode(NodeOpSyntaxCodeBlockElement, nil, yyDollar[2].node)
		}
	case 51:
		yyDollar = yyS[yypt-1 : yypt+1]
//line macro.y:222
		{
			yyVAL.node = newNode(NodeOpTypeDef, yyDollar[1].string)
		}
	case 52:
		yyDollar = yyS[yypt-4 : yypt+1]
//line macro.y:226
		{
			yyVAL.node = newNode(NodeOpTypeDef, yyDollar[1].string, yyDollar[3].node)
		}
	}
	goto yystack /* stack new state and value */
}
